version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      hashicorp:
        patterns:
          - "github.com/hashicorp/*"
      golang-org-x:
        patterns:
          - "golang.org/x/*"
      google:
        patterns:
          - "google.golang.org/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "actions/*"
      hashicorp:
        patterns:
          - "hashicorp/*"
