version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - depguard
    - lll
    - paralleltest
    - perfsprint
  settings:
    cyclop:
      max-complexity: 10
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
      disable-dec-order-check: false
      disable-init-func-first-check: false
    dupl:
      threshold: 150
    dupword:
      keywords:
        - the
        - and
        - a
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: fmt\.Print.*
        - pattern: fmt\.Print.*(# Do not commit print statements\.)?
    funlen:
      lines: 60
      statements: 40
    gocognit:
      min-complexity: 10
    gocyclo:
      min-complexity: 10
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/hashicorp/terraform-plugin-framework/datasource.DataSource
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - exhaustruct
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: internal/hmac/
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - lll
        source: '^//go:generate '
      - path: (.+)\.go$
        text: abcdef
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
